apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pdf-dep
  labels:
    app: pdffer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pdffer
  strategy: {}
  template:
    metadata:
      labels:
        app: pdffer
    spec:
      containers:
      - image: my-pdf-app:0.0.1-SNAPSHOT
        name: my-pdf-app
